repos:
  # Fix end of files
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args:
          - '--fix=lf'

  # Remove unused imports/variables
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          - "--in-place"
          - "--remove-all-unused-imports"
          - "--remove-unused-variable"
          - "--ignore-init-module-imports"

  # Sort imports
  - repo: https://github.com/pycqa/isort
    rev: "5.7.0"
    hooks:
      - id: isort
        args:
          - --profile
          - black

  # Black formatting
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black